export const mockShipments = [
  {
    id: "0JCudId6PS1GCea2EudbT",
    updatedAt: 1733341856000,
    phone: 43577094,
    products: [
      {
        cod: 28,
        category: "trenerka komplet",
        cop: 18,
        type: "Jordan",
        size: "M",
        color: "Black",
      },
    ],
    createdAt: 1729544250318,
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    receiverUserName: "",
    address: "Dardani ( Restaurant Jeta Stop) Capital Ria",
    city: "Gjakova",
    pieces: 1,
    xId: "X11714a12",
    status: "awaiting pickup",
    isPaid: false,
    country: "Kosova",
    receiverFullName: "Samanta Dushaj",
  },
  {
    id: "2oaQYQPOhpXVfwWKahC2k",
    receiverUserName: "X124a9271",
    status: "awaiting pickup",
    city: "Shtime",
    products: [
      {
        category: "trenerka komplet",
        size: "S",
        cod: 27,
        cop: 7,
        color: "Black",
        type: "Nike empty",
      },
    ],
    address: "rruga Tahir Sinani në Objekt Te viva fresh",
    isPaid: false,
    updatedAt: 1733255456000,
    pieces: 1,
    country: "Kosova",
    createdAt: 1732662000000,
    phone: 48338563,
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    receiverFullName: "X1249271",
    xId: "X1249271",
  },
  {
    id: "0JCudId6PS1GCe2EudbT",
    updatedAt: 1729632672358,
    phone: 43577094,
    products: [
      {
        cod: 28,
        category: "trenerka komplet",
        cop: 18,
        type: "Jordan",
        size: "M",
        color: "Black",
      },
    ],
    createdAt: 1729544250318,
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    receiverUserName: "",
    address: "Dardani ( Restaurant Jeta Stop) Capital Ria",
    city: "Gjakova",
    pieces: 1,
    xId: "X1171412",
    status: "awaiting pickup",
    isPaid: false,
    country: "Kosova",
    receiverFullName: "Samanta Dushaj",
  },
  {
    id: "2oaQYQPOhpXVfwWKhC2k",
    receiverUserName: "X1249271",
    status: "refuzed",
    city: "Shtime",
    products: [
      {
        category: "trenerka komplet",
        size: "S",
        cod: 27,
        cop: 7,
        color: "Black",
        type: "Nike empty",
      },
    ],
    address: "rruga Tahir Sinani në Objekt Te viva fresh",
    isPaid: false,
    updatedAt: 1732662000000,
    pieces: 1,
    country: "Kosova",
    createdAt: 1732662000000,
    phone: 48338563,
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    receiverFullName: "X1249271",
    xId: "X1249271",
  },
  {
    id: "3HKQhWPctw7ZIkjm77re",
    isPaid: false,
    city: "Prishtina",
    address: "RRUGA:LEC GRADICA TOKBASHQE",
    country: "Kosova",
    status: "refuzed",
    pieces: 1,
    receiverUserName: "",
    receiverFullName: "rubin hamiti",
    phone: 49666013,
    createdAt: 1729718530540,
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    xId: "X1174950",
    products: [
      {
        color: "Light Gray",
        type: "Trapstar",
        size: "L",
        category: "trenerka komplet",
        cod: 28,
        cop: 18,
      },
    ],
    updatedAt: 1729802558876,
  },
  {
    id: "6J0Ea65t6TteCPumc4QP",
    xId: "X1241614",
    updatedAt: 1732402800000,
    address: "",
    city: "Malishev",
    receiverUserName: "Edona",
    country: "Kosova",
    status: "in delivery",
    createdAt: 1732402800000,
    receiverFullName: "Edona",
    isPaid: false,
    products: [
      {
        color: "Light Gray",
        size: "XL",
        type: "Nike w/hoodie",
        cod: 27,
        category: "trenerka komplet",
        cop: 5,
      },
    ],
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    pieces: 1,
    phone: 44666079,
  },
  {
    id: "7su5WWh5D1pVTRvVZFcZ",
    address: "Bregu diellit proper Pica",
    city: "Prishtina",
    pieces: 1,
    status: "delivered",
    products: [
      {
        size: "XL",
        category: "trenerka komplet",
        cop: 7,
        color: "Black",
        type: "hugo",
        cod: 27,
      },
    ],
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    updatedAt: 1732662000000,
    receiverFullName: "Majlinda Ramadani",
    createdAt: 1732662000000,
    country: "Kosova",
    phone: 43709426,
    xId: "X1247168",
    receiverUserName: "Majlinda Ramadani",
    isPaid: false,
  },
  {
    id: "BNFw1pJr9LpS0JiJKaGM",
    phone: 49704609,
    products: [
      {
        type: "Trapstar",
        cod: 26,
        category: "trenerka komplet",
        color: "Light Gray",
        size: "XXL",
        cop: 18,
      },
      {
        size: "XXL",
        type: "Trapstar",
        cop: 18,
        color: "Black",
        category: "trenerka komplet",
        cod: 28,
      },
    ],
    status: "delivered",
    isPaid: false,
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    receiverFullName: "Perparim elezaj",
    address: "senoc rrg thanav",
    xId: "X1171416\t",
    country: "Kosova",
    createdAt: 1729544464384,
    city: "Rahovec",
    receiverUserName: "",
    updatedAt: 1729632661471,
    pieces: 2,
  },
  {
    id: "BX7H7NqCOg6ELvPt9djd",
    status: "delivered",
    updatedAt: 1732402800000,
    country: "Kosova",
    createdAt: 1732402800000,
    address: "Rruga shaqir kuka",
    xId: "X1244511",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    pieces: 1,
    phone: 45483962,
    city: "Kacanik",
    isPaid: false,
    products: [
      {
        color: "Black",
        category: "trenerka komplet",
        cop: 7,
        size: "XL",
        cod: 27,
        type: "LV",
      },
    ],
    receiverUserName: "Zekirja",
    receiverFullName: "Zekirja",
  },
  {
    id: "C3c7qlcZIhwKvWF56GH1",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    phone: 45397045,
    address: "Mazgit Te depo e Mikmik te kontinjerat e bardh\t",
    country: "Kosova",
    createdAt: 1729459142949,
    receiverFullName: "Valdrin bytyqi\t",
    receiverUserName: "",
    products: [
      {
        cop: 14,
        category: "trenerka komplet",
        type: "Nike letter",
        size: "L",
        color: "Light Red",
        cod: 28,
      },
    ],
    xId: "X1169320",
    updatedAt: 1729543898728,
    isPaid: false,
    status: "delivered",
    pieces: 1,
    city: "Obiliq",
  },
  {
    id: "GuNOYnFslBk19zsK9iUC",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    phone: 45528036,
    country: "Kosova",
    xId: "X1173169\t",
    status: "delivered",
    receiverUserName: "",
    pieces: 1,
    isPaid: false,
    city: "Hani i Elezit",
    receiverFullName: "Drilon hasallari",
    products: [
      {
        type: "Nike letter",
        category: "trenerka komplet",
        cod: 28,
        size: "M",
        cop: 20,
        color: "Light Gray",
      },
    ],
    address: "Lagja e re",
    createdAt: 1729632865313,
    updatedAt: 1729718314931,
  },
  {
    id: "KLPgLcMhwKt4HdteQ66X",
    createdAt: 1732662000000,
    products: [
      {
        cod: 27,
        type: "Nike empty",
        size: "L",
        cop: 7,
        color: "Black",
        category: "trenerka komplet",
      },
    ],
    xId: "X1249268",
    country: "Kosova",
    updatedAt: 1732662000000,
    city: "Peja",
    isPaid: false,
    pieces: 1,
    receiverFullName: "Shkodran ademaj",
    status: "delivered",
    receiverUserName: "Shkodran ademaj",
    address:
      "Istog Fshati lubov nr i shpis 46. Nr telit Beslim Ademaj rruga Fush mirr",
    phone: 45442446,
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
  },
  {
    id: "LHOuTfAzrTqVNOBEuIka",
    phone: 49182420,
    isPaid: false,
    xId: "X1247167",
    receiverUserName: "Kledi hameli",
    country: "Kosova",
    updatedAt: 1732662000000,
    createdAt: 1732662000000,
    products: [
      {
        cod: 27,
        color: "White",
        size: "L",
        category: "trenerka komplet",
        type: "Trapstar",
        cop: 7,
      },
    ],
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    status: "delivered",
    receiverFullName: "Kledi hameli",
    city: "Prizren",
    address: "fshati mazrek lagjia hamel",
    pieces: 1,
  },
  {
    id: "LP2qRZFn4oSUZjXBtk9n",
    products: [
      {
        category: "trenerka komplet",
        cop: 7,
        size: "S",
        type: "Trapstar",
        cod: 27,
        color: "Light Gray",
      },
    ],
    status: "delivered",
    createdAt: 1732748400000,
    isPaid: false,
    country: "Kosova",
    updatedAt: 1732748400000,
    receiverFullName: "Dion ibraj",
    pieces: 1,
    city: "Peja",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    phone: 44585967,
    address: "Radac te expresi",
    receiverUserName: "Dion ibraj",
    xId: "X1250663",
  },
  {
    id: "LhMsNp3q8rkbru95Kcl3",
    city: "Mitrovica",
    receiverFullName: "Medina ahmeti",
    status: "delivered",
    receiverUserName: "",
    updatedAt: 1729708588420,
    isPaid: false,
    xId: "X1173164",
    country: "Kosova",
    address: "rruga lek dukagjini te furra europa",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    products: [
      {
        size: "M",
        cod: 28,
        color: "Black",
        type: "Trapstar",
        category: "trenerka komplet",
        cop: 18,
      },
    ],
    createdAt: 1729632794752,
    phone: 43805677,
    pieces: 1,
  },
  {
    id: "MuuI8tWhKUT9AHyyMnRI",
    address: "rruga :Abdyl Frasheri, Astrazup",
    xId: "X1171418\t",
    country: "Kosova",
    status: "delivered",
    products: [
      {
        type: "Hoodrich",
        size: "M",
        cop: 18,
        category: "trenerka komplet",
        color: "Black",
        cod: 28,
      },
    ],
    pieces: 1,
    phone: 49197325,
    createdAt: 1729544534990,
    isPaid: false,
    updatedAt: 1729632699967,
    receiverFullName: "Olti morina",
    city: "Malishev",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    receiverUserName: "",
  },
  {
    id: "MwwWMUTYBOBBaRNZYv1k",
    isPaid: false,
    status: "delivered",
    pieces: 1,
    receiverFullName: "Elvir Syla",
    address: "Afer benidones",
    country: "Kosova",
    receiverUserName: "Elvir Syla",
    products: [
      {
        cop: 7,
        size: "XL",
        cod: 27,
        category: "trenerka komplet",
        type: "Trapstar",
        color: "Light Gray",
      },
    ],
    updatedAt: 1732575600000,
    createdAt: 1732575600000,
    city: "Podujeva",
    phone: 45523760,
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    xId: "X1246930",
  },
  {
    id: "R1xXJAh6sAsjzWQNcFO9",
    phone: 45688713,
    receiverFullName: "Unejs sadriu",
    updatedAt: 1729632708087,
    country: "Kosova",
    city: "Ferizaj",
    isPaid: false,
    createdAt: 1729544187347,
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    address: "rruga metush krasniniqi",
    status: "delivered",
    xId: "X1171411",
    products: [
      {
        type: "Nike empty",
        cop: 18,
        size: "XL",
        color: "Black",
        category: "trenerka komplet",
        cod: 28,
      },
    ],
    receiverUserName: "",
    pieces: 1,
  },
  {
    id: "RNBmyH8GKCQ773J91NNG",
    createdAt: 1729802771702,
    address: "Veterant e UCK-s",
    isPaid: false,
    city: "Hani i Elezit",
    receiverUserName: "",
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    country: "Kosova",
    products: [
      {
        type: "Nike letter",
        size: "M",
        color: "Light Gray",
        cod: 28,
        category: "trenerka komplet",
        cop: 20,
      },
    ],
    receiverFullName: "Xheladin hasallari",
    pieces: 1,
    phone: 45528036,
    status: "delivered",
    xId: "X1176644\t",
    updatedAt: 1729887786547,
  },
  {
    id: "V1WXSjOteUEh2M4HGyXv",
    phone: 43901718044720056,
    createdAt: 1730059776158,
    country: "Kosova",
    receiverFullName: "Blend selaj",
    address: "novoselle",
    status: "delivered",
    receiverUserName: "",
    xId: "X1176647",
    updatedAt: 1730061560162,
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    city: "Peja",
    pieces: 1,
    products: [
      {
        cod: 28,
        size: "XXL",
        type: "Trapstar",
        cop: 18,
        category: "trenerka komplet",
        color: "Black",
      },
    ],
    isPaid: false,
  },
  {
    id: "VlHaEXNqnTLfCLOShgvz",
    city: "Prishtina",
    status: "delivered",
    createdAt: 1732748400000,
    products: [
      {
        cop: 7,
        color: "Light Gray",
        size: "M",
        type: "Trapstar",
        category: "trenerka komplet",
        cod: 27,
      },
    ],
    address:
      "magjistralja prishtin podujev fshati besi rruga xhemajl osmani emri faik osmani",
    pieces: 1,
    receiverUserName: "Faik osmani",
    country: "Kosova",
    isPaid: false,
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    updatedAt: 1732748400000,
    xId: "X1250527",
    phone: 44690766,
    receiverFullName: "Faik osmani",
  },
  {
    id: "Wv6epCflgxUoqEOLLd7L",
    pieces: 1,
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    products: [
      {
        category: "trenerka komplet",
        type: "DG/MILANO",
        cod: 28,
        cop: 15,
        color: "Light Gray",
        size: "M",
      },
    ],
    xId: "X1169068",
    isPaid: false,
    phone: 46137225049854970,
    receiverFullName: "Altin Gashi",
    country: "Kosova",
    updatedAt: 1729543980600,
    status: "delivered",
    city: "Fushekosove",
    address:
      "Fshati Bardh i madh munesh mi lan tek marketi “SIMNICA” ne rrugen kryesore bardh i madh eshte.",
    receiverUserName: "",
    createdAt: 1729459387778,
  },
  {
    id: "X9pb04xcoZzCYuovFn2I",
    receiverFullName: "Enes kadiri",
    createdAt: 1732489200000,
    phone: 43904521,
    updatedAt: 1732489200000,
    products: [
      {
        color: "Light Gray",
        size: "L",
        cop: 5,
        type: "Nike w/hoodie",
        category: "trenerka komplet",
        cod: 27,
      },
    ],
    isPaid: false,
    xId: "X1244515",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    country: "Kosova",
    receiverUserName: "Enes kadiri",
    pieces: 1,
    address: "Ali Sokoli",
    status: "delivered",
    city: "Rahovec",
  },
  {
    id: "Xxjy1AUlwaBnqBKns3V8",
    receiverUserName: "Emine tara",
    address: "Mihedin tara",
    receiverFullName: "Emine tara",
    status: "delivered",
    isPaid: false,
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    city: "Rahovec",
    products: [
      {
        category: "trenerka komplet",
        cop: 7,
        size: "XL",
        type: "Puma",
        color: "Black",
        cod: 27,
      },
    ],
    xId: "X1249277",
    phone: 49330314,
    pieces: 1,
    updatedAt: 1732662000000,
    country: "Kosova",
    createdAt: 1732662000000,
  },
  {
    id: "YvcSizOi2lY1q6QA5qfp",
    country: "Kosova",
    status: "delivered",
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    receiverUserName: "",
    city: "Fushekosove",
    products: [
      {
        size: "XL",
        cop: 18,
        type: "Nike empty",
        color: "Black",
        category: "trenerka komplet",
        cod: 28,
      },
    ],
    isPaid: false,
    xId: "X1174946",
    pieces: 1,
    receiverFullName: "Ideal muhaxhiri",
    phone: 44646956,
    updatedAt: 1729887880212,
    address: "rruga dardania",
    createdAt: 1729718594119,
  },
  {
    id: "Z20cyV6utKTF0FsRhiGx",
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    phone: 45308443,
    receiverFullName: "Ariston Kasapi",
    pieces: 1,
    address: "Rr.Papa Klimenti Masa L",
    updatedAt: 1730059781828,
    xId: "X1181383",
    city: "Peja",
    createdAt: 1730059641185,
    products: [
      {
        cod: 28,
        color: "Light Gray",
        type: "Nike letter",
        cop: 20,
        category: "trenerka komplet",
        size: "L",
      },
    ],
    country: "Kosova",
    receiverUserName: "",
    status: "delivered",
    isPaid: false,
  },
  {
    id: "btrEaZfigKPv7qcv4taQ",
    country: "Kosova",
    isPaid: false,
    city: "Strpc",
    receiverFullName: "Jasna Sibinovic",
    receiverUserName: "Jasna Sibinovic",
    phone: 45545135,
    pieces: 1,
    status: "delivered",
    products: [
      {
        category: "trenerka komplet",
        cod: 27,
        type: "Nike w/hoodie",
        cop: 5,
        size: "L",
        color: "Black",
      },
    ],
    xId: "X1241616",
    address: "Street Staja Markovic Mbrama ni shkollw",
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    updatedAt: 1732402800000,
    createdAt: 1732402800000,
  },
  {
    id: "dojgZNPubhE80nebtYI7",
    isPaid: false,
    xId: "X1169075",
    status: "delivered",
    pieces: 1,
    address: "Frizren mili te ura e madhe",
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    products: [
      {
        category: "trenerka komplet",
        size: "XXL",
        color: "Black",
        type: "Jordan",
        cop: 18,
        cod: 28,
      },
    ],
    updatedAt: 1729543983000,
    receiverFullName: "Fatmir krasniqi",
    receiverUserName: "",
    phone: 49598677,
    country: "Kosova",
    city: "Malishev",
    createdAt: 1729459450303,
  },
  {
    id: "eOJUdQQHlefTchTW6o12",
    createdAt: 1732402800000,
    xId: "X1241626",
    city: "Rahovec",
    updatedAt: 1732402800000,
    address: "rruga Halil Hamza",
    receiverFullName: "Denisa Shehu",
    phone: 48250838,
    isPaid: false,
    products: [
      {
        category: "trenerka komplet",
        cod: 27,
        color: "Light Gray",
        size: "S",
        cop: 5,
        type: "Nike w/hoodie",
      },
    ],
    status: "delivered",
    country: "Kosova",
    receiverUserName: "Denisa Shehu",
    pieces: 1,
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
  },
  {
    id: "j6Bv8moINL9ljthKpluA",
    products: [
      {
        type: "North Face w/hoodie",
        size: "L",
        color: "Light Gray",
        cop: 5,
        category: "trenerka komplet",
        cod: 25,
      },
    ],
    xId: "X1241629",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    receiverFullName: "Agnesa Kaqiku",
    isPaid: false,
    phone: 49641988,
    address: "kqiq i vogel rruga liridashesit",
    pieces: 1,
    receiverUserName: "Agnesa Kaqiku",
    updatedAt: 1732402800000,
    city: "Mitrovica",
    country: "Kosova",
    status: "delivered",
    createdAt: 1732402800000,
  },
  {
    id: "juie6e0PlxD1BPEGnMcU",
    createdAt: 1729459199072,
    country: "Kosova",
    status: "delivered",
    pieces: 1,
    receiverFullName: "Ardonis zogaj\t",
    products: [
      {
        type: "Trapstar",
        color: "Black",
        cod: 28,
        cop: 18,
        size: "M",
        category: "trenerka komplet",
      },
    ],
    city: "Malishev",
    updatedAt: 1729543984616,
    isPaid: false,
    xId: "X1169057",
    address: "fshati lladroc rruga ali zogaj\t",
    phone: 43875892,
    receiverUserName: "",
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
  },
  {
    id: "k4B2YLMu75trss6VLSLr",
    createdAt: 1729718459055,
    address: " fshati Qyshk rruga Liridashesit",
    xId: "X1174956",
    country: "Kosova",
    status: "delivered",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    products: [
      {
        cop: 18,
        type: "Nike letter",
        cod: 28,
        category: "trenerka komplet",
        size: "L",
        color: "Black",
      },
    ],
    receiverFullName: "Avdullah lushi",
    city: "Peja",
    pieces: 1,
    phone: 49298028,
    isPaid: false,
    receiverUserName: "",
    updatedAt: 1729802556107,
  },
  {
    id: "l0YtHQxZt2GqD245CRPo",
    receiverFullName: "Aferdita Hasani",
    phone: 44520329,
    status: "delivered",
    address: "Rr.Ylvi Demiri nr 38",
    country: "Kosova",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    xId: "X1241627",
    isPaid: false,
    receiverUserName: "Aferdita Hasani",
    products: [
      {
        category: "trenerka komplet",
        size: "S",
        cod: 27,
        cop: 7,
        type: "La Costa",
        color: "Black",
      },
    ],
    city: "Viti",
    pieces: 1,
    createdAt: 1732402800000,
    updatedAt: 1732402800000,
  },
  {
    id: "lVEVDfnSrQs3GBLhpQBV",
    country: "Kosova",
    address: "hajrip abazi fshati brrut",
    phone: 43975279,
    isPaid: false,
    pieces: 1,
    updatedAt: 1732662000000,
    xId: "X1249261dra",
    city: "Dragash",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    status: "delivered",
    products: [
      {
        size: "L",
        cod: 27,
        color: "Light Red",
        type: "Jordan",
        cop: 7,
        category: "trenerka komplet",
      },
    ],
    receiverUserName: "X1249261",
    createdAt: 1732662000000,
    receiverFullName: "X1249261",
  },
  {
    id: "lvZl2kgOydOtNR4yjFCx",
    xId: "X1241704",
    receiverFullName: "klient",
    phone: 44960006,
    createdAt: 1732402800000,
    receiverUserName: "klient",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    pieces: 1,
    products: [
      {
        size: "XL",
        category: "trenerka komplet",
        cod: 27,
        cop: 5,
        color: "Light Gray",
        type: "North Face w/hoodie",
      },
    ],
    city: "Prizren",
    isPaid: false,
    updatedAt: 1732402800000,
    address: "Zhur",
    country: "Kosova",
    status: "delivered",
  },
  {
    id: "mxgbfei48Q2G3XTOXgZY",
    receiverUserName: "Ylli pireci",
    createdAt: 1732834800000,
    address: "besim shala",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    isPaid: false,
    receiverFullName: "Ylli pireci",
    country: "Kosova",
    pieces: 1,
    phone: 43831011,
    updatedAt: 1732834800000,
    xId: "X1250807",
    products: [
      {
        color: "Light Red",
        type: "Jordan",
        cop: 7,
        size: "L",
        category: "trenerka komplet",
        cod: 27,
      },
    ],
    city: "Prizren",
    status: "delivered",
  },
  {
    id: "n5IZeMaHeUhRaaKHlJG6",
    updatedAt: 1732575600000,
    city: "Podujeva",
    country: "Kosova",
    receiverFullName: "Fitore krasniqi",
    xId: "X1246909",
    createdAt: 1732575600000,
    isPaid: false,
    pieces: 1,
    products: [
      {
        cop: 7,
        size: "M",
        color: "White",
        category: "trenerka komplet",
        cod: 27,
        type: "Jordan",
      },
    ],
    address: "Fsh doberdol bedri gashi",
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    status: "delivered",
    phone: 44264974,
    receiverUserName: "Fitore krasniqi",
  },
  {
    id: "nJ0ytPCOZnFlJlrJJ1rN",
    country: "Kosova",
    isPaid: false,
    receiverUserName: "Klient",
    pieces: 1,
    city: "Tetovë",
    phone: 79270356,
    address: "Remzije Sulejmani",
    receiverFullName: "Klient",
    status: "delivered",
    xId: "X1237180",
    createdAt: 1732143600000,
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    products: [
      {
        size: "M",
        cop: 13,
        category: "trenerka komplet",
        type: "La Costa",
        color: "White",
        cod: 36,
      },
    ],
    updatedAt: 1732143600000,
  },
  {
    id: "naXMgD5oQjuVht4dd1uH",
    pieces: 1,
    createdAt: 1729802830631,
    products: [
      {
        cop: 18,
        category: "trenerka komplet",
        color: "Black",
        size: "XXL",
        type: "Hoodrich",
        cod: 28,
      },
    ],
    phone: 43901718044720056,
    country: "Kosova",
    updatedAt: 1729963115452,
    address: "Novozelle",
    status: "delivered",
    xId: "X1176647",
    receiverFullName: "Blend selaj",
    isPaid: false,
    city: "Peja",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    receiverUserName: "",
  },
  {
    id: "nrgUh4H04niFp82PsQpG",
    products: [
      {
        size: "S",
        color: "White",
        cop: 5,
        type: "stone island",
        category: "duks",
        cod: 18,
      },
      {
        category: "trenerka komplet",
        type: "La Costa",
        cop: 9,
        color: "Black",
        cod: 27,
        size: "L",
      },
    ],
    country: "Kosova",
    createdAt: 1732662000000,
    isPaid: false,
    xId: "X1249274",
    pieces: 2,
    updatedAt: 1732662000000,
    receiverUserName: "Jetmir selmani",
    address: "fshati dardani jetmir selmani rruga skifteri",
    phone: 45623045,
    receiverFullName: "Jetmir selmani",
    status: "delivered",
    city: "Ferizaj",
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
  },
  {
    id: "vHGtsAG3RwACOs7AGwKN",
    pieces: 1,
    isPaid: false,
    products: [
      {
        size: "XXL",
        cod: 28,
        type: "Nike empty",
        cop: 18,
        category: "trenerka komplet",
        color: "Black",
      },
    ],
    country: "Kosova",
    address: "Fahri aliu",
    receiverFullName: "Emin milano",
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    status: "delivered",
    receiverUserName: "",
    createdAt: 1729459515290,
    updatedAt: 1729543987000,
    phone: 49514347049301910,
    xId: "X1169084",
    city: "Mitrovica",
  },
  {
    id: "xYUwNw9tbsNXtFhsTJzW",
    isPaid: false,
    updatedAt: 1732662000000,
    receiverUserName: "Nemanja Kuzmanovic",
    createdAt: 1732662000000,
    country: "Kosova",
    receiverFullName: "Nemanja Kuzmanovic",
    pieces: 1,
    xId: "X1246924",
    products: [
      {
        type: "Nike w/hoodie",
        cod: 27,
        size: "L",
        cop: 5,
        category: "trenerka komplet",
        color: "Light Gray",
      },
    ],
    status: "delivered",
    createdBy: {
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
      email: "arbergashideveloper@gmail.com",
    },
    city: "Strpc",
    address: "Brezovica-Tandems",
    phone: 45100273,
  },
  {
    id: "yYtiwuhZWgxtyfUFp1N7",
    isPaid: false,
    phone: 45879960,
    receiverFullName: "Triumf",
    xId: "X1241632",
    createdAt: 1732402800000,
    status: "delivered",
    address: "Market bani",
    receiverUserName: "Triumf",
    country: "Kosova",
    products: [
      {
        type: "La Costa",
        cod: 27,
        cop: 7,
        category: "trenerka komplet",
        size: "S",
        color: "White",
      },
    ],
    createdBy: {
      email: "arbergashideveloper@gmail.com",
      id: "tvuabK2ep5b2kymmbUym2uOLL2l2",
    },
    updatedAt: 1732402800000,
    pieces: 1,
    city: "Prizren",
  },
];
